// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nolus/suspend/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgChangeSuspend struct {
	FromAddress string `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Suspend     bool   `protobuf:"varint,2,opt,name=suspend,proto3" json:"suspend,omitempty"`
	BlockHeight int64  `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *MsgChangeSuspend) Reset()         { *m = MsgChangeSuspend{} }
func (m *MsgChangeSuspend) String() string { return proto.CompactTextString(m) }
func (*MsgChangeSuspend) ProtoMessage()    {}
func (*MsgChangeSuspend) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda7a982fa57e103, []int{0}
}
func (m *MsgChangeSuspend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeSuspend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeSuspend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeSuspend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeSuspend.Merge(m, src)
}
func (m *MsgChangeSuspend) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeSuspend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeSuspend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeSuspend proto.InternalMessageInfo

func (m *MsgChangeSuspend) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgChangeSuspend) GetSuspend() bool {
	if m != nil {
		return m.Suspend
	}
	return false
}

func (m *MsgChangeSuspend) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type MsgChangeSuspendResponse struct {
}

func (m *MsgChangeSuspendResponse) Reset()         { *m = MsgChangeSuspendResponse{} }
func (m *MsgChangeSuspendResponse) String() string { return proto.CompactTextString(m) }
func (*MsgChangeSuspendResponse) ProtoMessage()    {}
func (*MsgChangeSuspendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eda7a982fa57e103, []int{1}
}
func (m *MsgChangeSuspendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgChangeSuspendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgChangeSuspendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgChangeSuspendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgChangeSuspendResponse.Merge(m, src)
}
func (m *MsgChangeSuspendResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgChangeSuspendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgChangeSuspendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgChangeSuspendResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgChangeSuspend)(nil), "nolus.suspend.v1beta1.MsgChangeSuspend")
	proto.RegisterType((*MsgChangeSuspendResponse)(nil), "nolus.suspend.v1beta1.MsgChangeSuspendResponse")
}

func init() { proto.RegisterFile("nolus/suspend/v1beta1/tx.proto", fileDescriptor_eda7a982fa57e103) }

var fileDescriptor_eda7a982fa57e103 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x86, 0xb3, 0x06, 0xfc, 0xd8, 0x53, 0x90, 0x80, 0x10, 0xae, 0x58, 0xe2, 0x35, 0xa6, 0x71,
	0x97, 0xd3, 0xc6, 0x56, 0x6d, 0x6c, 0xae, 0x89, 0x9d, 0xcd, 0x91, 0x8f, 0x31, 0x09, 0x26, 0x3b,
	0x21, 0xb3, 0x27, 0xa7, 0xbf, 0xc2, 0x9f, 0x65, 0x79, 0xa5, 0xa5, 0x24, 0x7f, 0x44, 0x92, 0xcb,
	0x09, 0x1e, 0x16, 0x57, 0xee, 0xf3, 0xec, 0xcc, 0xbc, 0xbc, 0x5c, 0x68, 0x2c, 0x16, 0xa4, 0x68,
	0x41, 0x15, 0xe8, 0x44, 0xbd, 0x4e, 0x23, 0x30, 0xe1, 0x54, 0x99, 0xa5, 0xac, 0x6a, 0x34, 0xe8,
	0x9c, 0xf5, 0x5e, 0x0e, 0x5e, 0x0e, 0x7e, 0x52, 0xf3, 0xd3, 0x19, 0xa5, 0xf7, 0x59, 0xa8, 0x53,
	0x78, 0x5c, 0x3b, 0xe7, 0x9c, 0x1f, 0x3f, 0xd7, 0x58, 0xce, 0xc3, 0x24, 0xa9, 0x81, 0xc8, 0x65,
	0x1e, 0xf3, 0x8f, 0x82, 0x51, 0xc7, 0x6e, 0xd7, 0xc8, 0x71, 0xf9, 0xc1, 0xb0, 0xc9, 0xdd, 0xf3,
	0x98, 0x7f, 0x18, 0x6c, 0x9e, 0xdd, 0x70, 0x54, 0x60, 0xfc, 0x32, 0xcf, 0x20, 0x4f, 0x33, 0xe3,
	0xda, 0x1e, 0xf3, 0xed, 0x60, 0xd4, 0xb3, 0x87, 0x1e, 0x4d, 0xc6, 0xdc, 0xdd, 0xbe, 0x19, 0x00,
	0x55, 0xa8, 0x09, 0xae, 0x2a, 0x6e, 0xcf, 0x28, 0x75, 0x72, 0x7e, 0xf2, 0x37, 0xd3, 0x85, 0xfc,
	0x37, 0xbf, 0xdc, 0x5e, 0x34, 0x56, 0x3b, 0x7e, 0xdc, 0x5c, 0xbc, 0x0b, 0x3e, 0x1b, 0xc1, 0x56,
	0x8d, 0x60, 0xdf, 0x8d, 0x60, 0x1f, 0xad, 0xb0, 0x56, 0xad, 0xb0, 0xbe, 0x5a, 0x61, 0x3d, 0xdd,
	0xa4, 0xb9, 0x29, 0xc2, 0xe8, 0x52, 0x63, 0x89, 0x32, 0xae, 0x21, 0xc9, 0x89, 0xf2, 0x12, 0xa5,
	0x06, 0xa3, 0x3a, 0xa6, 0x62, 0xa4, 0xf2, 0x1d, 0x35, 0xa8, 0xe5, 0x6f, 0xef, 0xe6, 0xad, 0x02,
	0x8a, 0xf6, 0xfb, 0xce, 0xaf, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x69, 0x89, 0xe8, 0x3e, 0x95,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ChangeSuspend(ctx context.Context, in *MsgChangeSuspend, opts ...grpc.CallOption) (*MsgChangeSuspendResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ChangeSuspend(ctx context.Context, in *MsgChangeSuspend, opts ...grpc.CallOption) (*MsgChangeSuspendResponse, error) {
	out := new(MsgChangeSuspendResponse)
	err := c.cc.Invoke(ctx, "/nolus.suspend.v1beta1.Msg/ChangeSuspend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ChangeSuspend(context.Context, *MsgChangeSuspend) (*MsgChangeSuspendResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ChangeSuspend(ctx context.Context, req *MsgChangeSuspend) (*MsgChangeSuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeSuspend not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ChangeSuspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChangeSuspend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChangeSuspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nolus.suspend.v1beta1.Msg/ChangeSuspend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChangeSuspend(ctx, req.(*MsgChangeSuspend))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nolus.suspend.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeSuspend",
			Handler:    _Msg_ChangeSuspend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nolus/suspend/v1beta1/tx.proto",
}

func (m *MsgChangeSuspend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeSuspend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeSuspend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.Suspend {
		i--
		if m.Suspend {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgChangeSuspendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgChangeSuspendResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgChangeSuspendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgChangeSuspend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Suspend {
		n += 2
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	return n
}

func (m *MsgChangeSuspendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgChangeSuspend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeSuspend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeSuspend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Suspend", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Suspend = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgChangeSuspendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgChangeSuspendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgChangeSuspendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
