// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: nolus/contractmanager/query.proto

package contractmanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName          = "/nolus.contractmanager.Query/Params"
	Query_AddressFailure_FullMethodName  = "/nolus.contractmanager.Query/AddressFailure"
	Query_AddressFailures_FullMethodName = "/nolus.contractmanager.Query/AddressFailures"
	Query_Failures_FullMethodName        = "/nolus.contractmanager.Query/Failures"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Failure by contract address and failure ID.
	AddressFailure(ctx context.Context, in *QueryFailureRequest, opts ...grpc.CallOption) (*QueryAddressFailureResponse, error)
	// Queries Failures by contract address.
	AddressFailures(ctx context.Context, in *QueryFailuresByAddressRequest, opts ...grpc.CallOption) (*QueryAddressFailuresResponse, error)
	// Queries a list of Failures occurred on the network.
	Failures(ctx context.Context, in *QueryFailuresRequest, opts ...grpc.CallOption) (*QueryFailuresResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AddressFailure(ctx context.Context, in *QueryFailureRequest, opts ...grpc.CallOption) (*QueryAddressFailureResponse, error) {
	out := new(QueryAddressFailureResponse)
	err := c.cc.Invoke(ctx, Query_AddressFailure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AddressFailures(ctx context.Context, in *QueryFailuresByAddressRequest, opts ...grpc.CallOption) (*QueryAddressFailuresResponse, error) {
	out := new(QueryAddressFailuresResponse)
	err := c.cc.Invoke(ctx, Query_AddressFailures_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Failures(ctx context.Context, in *QueryFailuresRequest, opts ...grpc.CallOption) (*QueryFailuresResponse, error) {
	out := new(QueryFailuresResponse)
	err := c.cc.Invoke(ctx, Query_Failures_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Failure by contract address and failure ID.
	AddressFailure(context.Context, *QueryFailureRequest) (*QueryAddressFailureResponse, error)
	// Queries Failures by contract address.
	AddressFailures(context.Context, *QueryFailuresByAddressRequest) (*QueryAddressFailuresResponse, error)
	// Queries a list of Failures occurred on the network.
	Failures(context.Context, *QueryFailuresRequest) (*QueryFailuresResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) AddressFailure(context.Context, *QueryFailureRequest) (*QueryAddressFailureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressFailure not implemented")
}
func (UnimplementedQueryServer) AddressFailures(context.Context, *QueryFailuresByAddressRequest) (*QueryAddressFailuresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressFailures not implemented")
}
func (UnimplementedQueryServer) Failures(context.Context, *QueryFailuresRequest) (*QueryFailuresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Failures not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AddressFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AddressFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AddressFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AddressFailure(ctx, req.(*QueryFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AddressFailures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFailuresByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AddressFailures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AddressFailures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AddressFailures(ctx, req.(*QueryFailuresByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Failures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFailuresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Failures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Failures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Failures(ctx, req.(*QueryFailuresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nolus.contractmanager.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AddressFailure",
			Handler:    _Query_AddressFailure_Handler,
		},
		{
			MethodName: "AddressFailures",
			Handler:    _Query_AddressFailures_Handler,
		},
		{
			MethodName: "Failures",
			Handler:    _Query_Failures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nolus/contractmanager/query.proto",
}
