run:
  tests: false
  concurrency: 4
  timeout: 5m
  skip-dirs:
    - build # docker files
    - .cicd #
    - doc

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Enable linters that are disabled by default 
    - asciicheck
    - bidichk
    - bodyclose
    - godot
    - gofmt
    - gofumpt
    - goimports
    - misspell
    - whitespace
    - unused
    - ineffassign

output:
  # Sort results by: filepath, line and column.
  sort-results: true

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
