version: "2"

run:
  tests: false
  concurrency: 4
  timeout: 5m

linters:
  default: none
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Enable linters that are disabled by default 
    - asciicheck
    - bidichk
    - bodyclose
    - godot
    - misspell
    - whitespace
    - unused
    - ineffassign

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    paths:
      - build # docker files
      - .cicd #
      - doc