// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nolus/transfer/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v8/modules/apps/transfer/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("nolus/transfer/v1/query.proto", fileDescriptor_2e0cb6fb2f98ef40) }

var fileDescriptor_2e0cb6fb2f98ef40 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc6, 0xd7, 0x81, 0x03, 0x7b, 0xf0, 0x90, 0x63, 0x99, 0x39, 0x88, 0x07, 0x11, 0x97, 0xd8,
	0x4d, 0x5f, 0x40, 0x3c, 0x78, 0xd2, 0xe9, 0xd1, 0x8b, 0xa4, 0x31, 0xb6, 0x81, 0x36, 0xff, 0x2c,
	0x49, 0x87, 0x43, 0xbc, 0xf8, 0x04, 0xc2, 0xde, 0xc2, 0x27, 0x11, 0x4f, 0x03, 0x2f, 0x1e, 0xa5,
	0xf5, 0x41, 0xa4, 0xed, 0x36, 0x15, 0x14, 0xdc, 0x31, 0xf9, 0xbe, 0x2f, 0xdf, 0x8f, 0x7c, 0xfe,
	0xa6, 0x82, 0x34, 0xb7, 0xd4, 0x19, 0xa6, 0xec, 0x8d, 0x30, 0x74, 0x1c, 0xd2, 0x51, 0x2e, 0xcc,
	0x84, 0x68, 0x03, 0x0e, 0xd0, 0x46, 0x2d, 0x93, 0x85, 0x1c, 0x74, 0x63, 0x80, 0x38, 0x15, 0x94,
	0x69, 0x49, 0x99, 0x52, 0xe0, 0x98, 0x93, 0xa0, 0x6c, 0xe3, 0x0e, 0x76, 0x64, 0xc4, 0x29, 0xd3,
	0x3a, 0x95, 0xbc, 0xb9, 0xff, 0xeb, 0xdd, 0xfe, 0x4b, 0xdb, 0x5f, 0x3b, 0xaf, 0xce, 0x68, 0xea,
	0xf9, 0x9d, 0x21, 0x33, 0x2c, 0xb3, 0x68, 0x9f, 0xc8, 0x88, 0x93, 0xef, 0xf9, 0x65, 0x31, 0x19,
	0x87, 0xa4, 0xf6, 0x37, 0xd6, 0x0b, 0x31, 0xca, 0x85, 0x75, 0x41, 0xb8, 0x42, 0xc2, 0x6a, 0x50,
	0x56, 0x6c, 0x6d, 0x3f, 0xbc, 0x7e, 0x4c, 0xdb, 0x18, 0x75, 0xe9, 0x1c, 0xf6, 0x27, 0xa4, 0x6e,
	0x50, 0x9e, 0x3c, 0x7f, 0xfd, 0x58, 0x28, 0xc8, 0x4e, 0x98, 0x4d, 0xd0, 0xe0, 0x1f, 0x35, 0x4b,
	0xf7, 0x82, 0xed, 0x60, 0xb5, 0xd0, 0x1c, 0xaf, 0x5f, 0xe3, 0xed, 0xa1, 0xdd, 0xdf, 0xf1, 0xae,
	0xab, 0xc0, 0x55, 0xc2, 0x6c, 0x22, 0x2c, 0xbd, 0x73, 0x86, 0x71, 0x71, 0x7f, 0x74, 0xf6, 0x5c,
	0x60, 0x6f, 0x56, 0x60, 0xef, 0xbd, 0xc0, 0xde, 0x63, 0x89, 0x5b, 0xb3, 0x12, 0xb7, 0xde, 0x4a,
	0xdc, 0xba, 0x3c, 0x8c, 0xa5, 0x4b, 0xf2, 0x88, 0x70, 0xc8, 0xe8, 0x69, 0xb5, 0x64, 0x6f, 0x58,
	0x7d, 0x3f, 0x87, 0x94, 0xd6, 0xc3, 0xf6, 0x38, 0x18, 0x41, 0x6f, 0xbf, 0x2a, 0xdc, 0x44, 0x0b,
	0x1b, 0x75, 0xea, 0x91, 0x06, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x81, 0xcc, 0x0d, 0xbc, 0x1d,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries all parameters of the ibc-transfer module.
	Params(ctx context.Context, in *types.QueryParamsRequest, opts ...grpc.CallOption) (*types.QueryParamsResponse, error)
	// DenomHash queries a denomination hash information.
	DenomHash(ctx context.Context, in *types.QueryDenomHashRequest, opts ...grpc.CallOption) (*types.QueryDenomHashResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *types.QueryParamsRequest, opts ...grpc.CallOption) (*types.QueryParamsResponse, error) {
	out := new(types.QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/nolus.transfer.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DenomHash(ctx context.Context, in *types.QueryDenomHashRequest, opts ...grpc.CallOption) (*types.QueryDenomHashResponse, error) {
	out := new(types.QueryDenomHashResponse)
	err := c.cc.Invoke(ctx, "/nolus.transfer.Query/DenomHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries all parameters of the ibc-transfer module.
	Params(context.Context, *types.QueryParamsRequest) (*types.QueryParamsResponse, error)
	// DenomHash queries a denomination hash information.
	DenomHash(context.Context, *types.QueryDenomHashRequest) (*types.QueryDenomHashResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *types.QueryParamsRequest) (*types.QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) DenomHash(ctx context.Context, req *types.QueryDenomHashRequest) (*types.QueryDenomHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DenomHash not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nolus.transfer.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*types.QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DenomHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.QueryDenomHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DenomHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nolus.transfer.Query/DenomHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DenomHash(ctx, req.(*types.QueryDenomHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nolus.transfer.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DenomHash",
			Handler:    _Query_DenomHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nolus/transfer/v1/query.proto",
}
