// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nolus/tax/v2/params.proto

package typesv2

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the v2 parameters for the module.
type Params struct {
	FeeRate         int32           `protobuf:"varint,1,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	BaseDenom       string          `protobuf:"bytes,2,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty"`
	DexFeeParams    []*DexFeeParams `protobuf:"bytes,3,rep,name=dex_fee_params,json=dexFeeParams,proto3" json:"dex_fee_params,omitempty"`
	TreasuryAddress string          `protobuf:"bytes,4,opt,name=treasury_address,json=treasuryAddress,proto3" json:"treasury_address,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a30e19b46b1391, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFeeRate() int32 {
	if m != nil {
		return m.FeeRate
	}
	return 0
}

func (m *Params) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

func (m *Params) GetDexFeeParams() []*DexFeeParams {
	if m != nil {
		return m.DexFeeParams
	}
	return nil
}

func (m *Params) GetTreasuryAddress() string {
	if m != nil {
		return m.TreasuryAddress
	}
	return ""
}

// Defines the accepted fees with corresponding min prices and profit addresses
type DexFeeParams struct {
	ProfitAddress           string        `protobuf:"bytes,1,opt,name=profit_address,json=profitAddress,proto3" json:"profit_address,omitempty"`
	AcceptedDenomsMinPrices []*DenomPrice `protobuf:"bytes,2,rep,name=accepted_denoms_min_prices,json=acceptedDenomsMinPrices,proto3" json:"accepted_denoms_min_prices,omitempty"`
}

func (m *DexFeeParams) Reset()         { *m = DexFeeParams{} }
func (m *DexFeeParams) String() string { return proto.CompactTextString(m) }
func (*DexFeeParams) ProtoMessage()    {}
func (*DexFeeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a30e19b46b1391, []int{1}
}
func (m *DexFeeParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DexFeeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DexFeeParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DexFeeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexFeeParams.Merge(m, src)
}
func (m *DexFeeParams) XXX_Size() int {
	return m.Size()
}
func (m *DexFeeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DexFeeParams.DiscardUnknown(m)
}

var xxx_messageInfo_DexFeeParams proto.InternalMessageInfo

func (m *DexFeeParams) GetProfitAddress() string {
	if m != nil {
		return m.ProfitAddress
	}
	return ""
}

func (m *DexFeeParams) GetAcceptedDenomsMinPrices() []*DenomPrice {
	if m != nil {
		return m.AcceptedDenomsMinPrices
	}
	return nil
}

// DenomPrice will be used to define accepted denoms, their min prices and their ticker.
type DenomPrice struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// ticker will only be used for a more readable format for the users
	Ticker   string `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	MinPrice string `protobuf:"bytes,3,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
}

func (m *DenomPrice) Reset()         { *m = DenomPrice{} }
func (m *DenomPrice) String() string { return proto.CompactTextString(m) }
func (*DenomPrice) ProtoMessage()    {}
func (*DenomPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1a30e19b46b1391, []int{2}
}
func (m *DenomPrice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomPrice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomPrice.Merge(m, src)
}
func (m *DenomPrice) XXX_Size() int {
	return m.Size()
}
func (m *DenomPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomPrice.DiscardUnknown(m)
}

var xxx_messageInfo_DenomPrice proto.InternalMessageInfo

func (m *DenomPrice) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DenomPrice) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *DenomPrice) GetMinPrice() string {
	if m != nil {
		return m.MinPrice
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "nolus.tax.v2.Params")
	proto.RegisterType((*DexFeeParams)(nil), "nolus.tax.v2.DexFeeParams")
	proto.RegisterType((*DenomPrice)(nil), "nolus.tax.v2.DenomPrice")
}

func init() { proto.RegisterFile("nolus/tax/v2/params.proto", fileDescriptor_e1a30e19b46b1391) }

var fileDescriptor_e1a30e19b46b1391 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xad, 0xb7, 0xbb, 0x65, 0x3b, 0x94, 0x82, 0xac, 0x15, 0xa4, 0x91, 0x08, 0x55, 0x25, 0xa4,
	0x22, 0xd4, 0x44, 0x0a, 0x37, 0x4e, 0xb0, 0xaa, 0x38, 0x01, 0xaa, 0x22, 0x71, 0xe1, 0x12, 0xb9,
	0xce, 0x34, 0x44, 0x6c, 0xe2, 0xc8, 0x76, 0xab, 0xec, 0x3f, 0x70, 0xe0, 0xc8, 0x91, 0x8f, 0x80,
	0x7f, 0xe0, 0xb8, 0xe2, 0xc4, 0x11, 0xb5, 0x3f, 0x82, 0x6c, 0xa7, 0xa5, 0xda, 0x9b, 0xdf, 0x7b,
	0xf3, 0x3c, 0xcf, 0x9e, 0x81, 0x51, 0x25, 0xae, 0xd6, 0x2a, 0xd2, 0xac, 0x89, 0x36, 0x71, 0x54,
	0x33, 0xc9, 0x4a, 0x15, 0xd6, 0x52, 0x68, 0x41, 0x07, 0x56, 0x0a, 0x35, 0x6b, 0xc2, 0x4d, 0xec,
	0x5f, 0xe4, 0x22, 0x17, 0x56, 0x88, 0xcc, 0xc9, 0xd5, 0xf8, 0x23, 0x2e, 0x54, 0x29, 0x54, 0xea,
	0x04, 0x07, 0x9c, 0x34, 0xf9, 0x49, 0xa0, 0xb7, 0xb0, 0xf7, 0xd1, 0x11, 0x9c, 0xaf, 0x10, 0x53,
	0xc9, 0x34, 0x7a, 0x64, 0x4c, 0xa6, 0x67, 0xc9, 0x9d, 0x15, 0x62, 0xc2, 0x34, 0xd2, 0xc7, 0x00,
	0x4b, 0xa6, 0x30, 0xcd, 0xb0, 0x12, 0xa5, 0x77, 0x32, 0x26, 0xd3, 0x7e, 0xd2, 0x37, 0xcc, 0xdc,
	0x10, 0xf4, 0x15, 0x0c, 0x33, 0x6c, 0x52, 0xe3, 0x76, 0xd9, 0xbc, 0xee, 0xb8, 0x3b, 0xbd, 0x1b,
	0xfb, 0xe1, 0x71, 0xb8, 0x70, 0x8e, 0xcd, 0x1b, 0x44, 0xd7, 0x2d, 0x19, 0x64, 0x47, 0x88, 0x3e,
	0x83, 0x07, 0x5a, 0x22, 0x53, 0x6b, 0x79, 0x9d, 0xb2, 0x2c, 0x93, 0xa8, 0x94, 0x77, 0x6a, 0xdb,
	0xdc, 0xdf, 0xf3, 0xaf, 0x1d, 0xfd, 0xf2, 0xf4, 0xdb, 0xf7, 0x27, 0x64, 0xf2, 0x85, 0xc0, 0xe0,
	0xf8, 0x3e, 0xfa, 0x14, 0x86, 0xb5, 0x14, 0xab, 0x42, 0x1f, 0xfc, 0xc4, 0xfa, 0xef, 0x39, 0xb6,
	0x75, 0xd3, 0x0f, 0xe0, 0x33, 0xce, 0xb1, 0xd6, 0x98, 0xb9, 0xd7, 0xa8, 0xb4, 0x2c, 0xaa, 0xb4,
	0x96, 0x05, 0x47, 0xe5, 0x9d, 0xd8, 0xd8, 0xde, 0xed, 0xd8, 0x95, 0x28, 0x17, 0xa6, 0x20, 0x79,
	0xb4, 0xf7, 0x5a, 0x4e, 0xbd, 0x2b, 0x2a, 0xcb, 0xab, 0x49, 0x0e, 0xf0, 0xbf, 0x8c, 0x5e, 0xc0,
	0x99, 0xfb, 0x29, 0x17, 0xc1, 0x01, 0xfa, 0x10, 0x7a, 0xba, 0xe0, 0x9f, 0x51, 0xb6, 0x1f, 0xd8,
	0x22, 0xfa, 0x1c, 0xfa, 0x87, 0x08, 0x5e, 0xd7, 0x48, 0x97, 0xc3, 0xdf, 0x3f, 0x66, 0xd0, 0xce,
	0x69, 0x8e, 0x3c, 0x39, 0x2f, 0xdb, 0x4e, 0x97, 0x6f, 0x7f, 0x6d, 0x03, 0x72, 0xb3, 0x0d, 0xc8,
	0xdf, 0x6d, 0x40, 0xbe, 0xee, 0x82, 0xce, 0xcd, 0x2e, 0xe8, 0xfc, 0xd9, 0x05, 0x9d, 0x8f, 0x71,
	0x5e, 0xe8, 0x4f, 0xeb, 0x65, 0xc8, 0x45, 0x19, 0xbd, 0x37, 0xf9, 0x67, 0x0b, 0x33, 0x61, 0x2e,
	0xae, 0x22, 0xfb, 0x9c, 0x19, 0x17, 0x12, 0xa3, 0xc6, 0x2e, 0x91, 0xbe, 0xae, 0x51, 0x6d, 0xe2,
	0x65, 0xcf, 0x2e, 0xc1, 0x8b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x29, 0x11, 0xb9, 0x60,
	0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TreasuryAddress) > 0 {
		i -= len(m.TreasuryAddress)
		copy(dAtA[i:], m.TreasuryAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TreasuryAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DexFeeParams) > 0 {
		for iNdEx := len(m.DexFeeParams) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DexFeeParams[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0x12
	}
	if m.FeeRate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeRate))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DexFeeParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DexFeeParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DexFeeParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AcceptedDenomsMinPrices) > 0 {
		for iNdEx := len(m.AcceptedDenomsMinPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AcceptedDenomsMinPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ProfitAddress) > 0 {
		i -= len(m.ProfitAddress)
		copy(dAtA[i:], m.ProfitAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProfitAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DenomPrice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomPrice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomPrice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinPrice) > 0 {
		i -= len(m.MinPrice)
		copy(dAtA[i:], m.MinPrice)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinPrice)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Ticker) > 0 {
		i -= len(m.Ticker)
		copy(dAtA[i:], m.Ticker)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Ticker)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FeeRate != 0 {
		n += 1 + sovParams(uint64(m.FeeRate))
	}
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.DexFeeParams) > 0 {
		for _, e := range m.DexFeeParams {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = len(m.TreasuryAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *DexFeeParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProfitAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.AcceptedDenomsMinPrices) > 0 {
		for _, e := range m.AcceptedDenomsMinPrices {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *DenomPrice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Ticker)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MinPrice)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeRate", wireType)
			}
			m.FeeRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeRate |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexFeeParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DexFeeParams = append(m.DexFeeParams, &DexFeeParams{})
			if err := m.DexFeeParams[len(m.DexFeeParams)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreasuryAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DexFeeParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DexFeeParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DexFeeParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfitAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProfitAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedDenomsMinPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptedDenomsMinPrices = append(m.AcceptedDenomsMinPrices, &DenomPrice{})
			if err := m.AcceptedDenomsMinPrices[len(m.AcceptedDenomsMinPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenomPrice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomPrice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomPrice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ticker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ticker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
