project:
  name: Nolus
  tz: Europe/Sofia
  adrFolder: ./adr
  packages:
    - name: Cosmos-Zone
      path: ./cosmzone
      adrFolder: ./cosmzone/adr
    # - name: Smart-Contracts
    #   path: ./smart-contracts
    #   adrFolder: ./smart-contracts/adr
    # - name: Application-Server
    #   path: ./appserver
    #   adrFolder: ./appserver/adr
    # - name: Web-UI
    #   path: ./web-ui
    #   adrFolder: ./web-ui/adr
