// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nolus/interchainqueries/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// Defines amount of blocks required before query becomes available for
	// removal by anybody
	QuerySubmitTimeout uint64 `protobuf:"varint,1,opt,name=query_submit_timeout,json=querySubmitTimeout,proto3" json:"query_submit_timeout,omitempty"`
	// Amount of coins deposited for the query.
	QueryDeposit github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=query_deposit,json=queryDeposit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"query_deposit"`
	// Amount of tx hashes to be removed during a single EndBlock. Can vary to
	// balance between network cleaning speed and EndBlock duration. A zero value
	// means no limit.
	TxQueryRemovalLimit uint64 `protobuf:"varint,3,opt,name=tx_query_removal_limit,json=txQueryRemovalLimit,proto3" json:"tx_query_removal_limit,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d55c724307965f46, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetQuerySubmitTimeout() uint64 {
	if m != nil {
		return m.QuerySubmitTimeout
	}
	return 0
}

func (m *Params) GetQueryDeposit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.QueryDeposit
	}
	return nil
}

func (m *Params) GetTxQueryRemovalLimit() uint64 {
	if m != nil {
		return m.TxQueryRemovalLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "nolus.interchainqueries.Params")
}

func init() {
	proto.RegisterFile("nolus/interchainqueries/params.proto", fileDescriptor_d55c724307965f46)
}

var fileDescriptor_d55c724307965f46 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0xfa, 0x40,
	0x18, 0xc7, 0xdb, 0x1f, 0x84, 0xa1, 0x3f, 0x5d, 0x2a, 0x51, 0x64, 0x38, 0x88, 0x71, 0x60, 0xe1,
	0x0e, 0x64, 0x73, 0x70, 0x40, 0x47, 0x63, 0x10, 0x1d, 0x8c, 0x4b, 0xd3, 0x96, 0x0b, 0x5c, 0xec,
	0xf5, 0xa9, 0xbd, 0xa7, 0x04, 0xde, 0x85, 0xa3, 0xa3, 0xb3, 0xaf, 0x84, 0x91, 0xd1, 0x49, 0x0d,
	0x1d, 0x7c, 0x1b, 0xe6, 0xee, 0x18, 0x4c, 0x74, 0xea, 0x93, 0x7e, 0x9e, 0x3f, 0x9f, 0x7c, 0xcf,
	0x3b, 0x4e, 0x21, 0x29, 0x14, 0x13, 0x29, 0xf2, 0x3c, 0x9e, 0x85, 0x22, 0x7d, 0x2c, 0x78, 0x2e,
	0xb8, 0x62, 0x59, 0x98, 0x87, 0x52, 0xd1, 0x2c, 0x07, 0x04, 0xff, 0xc0, 0x74, 0xd1, 0x5f, 0x5d,
	0x4d, 0x12, 0x83, 0x92, 0xa0, 0x58, 0x14, 0x2a, 0xce, 0xe6, 0xfd, 0x88, 0x63, 0xd8, 0x67, 0x31,
	0x88, 0xd4, 0x0e, 0x36, 0xeb, 0x53, 0x98, 0x82, 0x29, 0x99, 0xae, 0xec, 0xdf, 0xa3, 0x2f, 0xd7,
	0xab, 0x8d, 0xcc, 0x7e, 0xbf, 0xe7, 0xd5, 0xf5, 0xae, 0x65, 0xa0, 0x8a, 0x48, 0x0a, 0x0c, 0x50,
	0x48, 0x0e, 0x05, 0x36, 0xdc, 0xb6, 0xdb, 0xa9, 0x8e, 0x7d, 0xc3, 0x6e, 0x0c, 0xba, 0xb5, 0xc4,
	0xcf, 0xbc, 0x5d, 0x3b, 0x31, 0xe1, 0x19, 0x28, 0x81, 0x8d, 0x7f, 0xed, 0x4a, 0xe7, 0xff, 0xc9,
	0x21, 0xb5, 0x2a, 0x54, 0xab, 0xd0, 0xad, 0x0a, 0x3d, 0x07, 0x91, 0x0e, 0x7b, 0xab, 0xf7, 0x96,
	0xf3, 0xfa, 0xd1, 0xea, 0x4c, 0x05, 0xce, 0x8a, 0x88, 0xc6, 0x20, 0xd9, 0xd6, 0xdb, 0x7e, 0xba,
	0x6a, 0xf2, 0xc0, 0x70, 0x99, 0x71, 0x65, 0x06, 0xd4, 0x78, 0xc7, 0x5c, 0xb8, 0xb0, 0x07, 0xfc,
	0x81, 0xb7, 0x8f, 0x8b, 0xc0, 0x1e, 0xcd, 0xb9, 0x84, 0x79, 0x98, 0x04, 0x89, 0x90, 0x02, 0x1b,
	0x15, 0x63, 0xb9, 0x87, 0x8b, 0x6b, 0x0d, 0xc7, 0x96, 0x5d, 0x6a, 0x74, 0x5a, 0x7d, 0x7e, 0x69,
	0x39, 0xc3, 0xbb, 0xd5, 0x86, 0xb8, 0xeb, 0x0d, 0x71, 0x3f, 0x37, 0xc4, 0x7d, 0x2a, 0x89, 0xb3,
	0x2e, 0x89, 0xf3, 0x56, 0x12, 0xe7, 0xfe, 0xec, 0x87, 0xcc, 0x95, 0x4e, 0xb7, 0x3b, 0xd2, 0xd9,
	0xc4, 0x90, 0x30, 0x13, 0x76, 0x37, 0x86, 0x9c, 0xb3, 0xc5, 0x1f, 0x2f, 0x63, 0x44, 0xa3, 0x9a,
	0x89, 0x72, 0xf0, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x36, 0x58, 0x0d, 0xec, 0xc1, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxQueryRemovalLimit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TxQueryRemovalLimit))
		i--
		dAtA[i] = 0x18
	}
	if len(m.QueryDeposit) > 0 {
		for iNdEx := len(m.QueryDeposit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.QueryDeposit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.QuerySubmitTimeout != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.QuerySubmitTimeout))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.QuerySubmitTimeout != 0 {
		n += 1 + sovParams(uint64(m.QuerySubmitTimeout))
	}
	if len(m.QueryDeposit) > 0 {
		for _, e := range m.QueryDeposit {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.TxQueryRemovalLimit != 0 {
		n += 1 + sovParams(uint64(m.TxQueryRemovalLimit))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuerySubmitTimeout", wireType)
			}
			m.QuerySubmitTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuerySubmitTimeout |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryDeposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryDeposit = append(m.QueryDeposit, types.Coin{})
			if err := m.QueryDeposit[len(m.QueryDeposit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxQueryRemovalLimit", wireType)
			}
			m.TxQueryRemovalLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxQueryRemovalLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
