name: Deploy dev network
# Builds new binary and deploy on dev network on a new version only.
# A version is denoted with a protected tag.
on:
  push:
    # Only tags which match the protected tag pattern will trigger this workflow
    tags:
      - v*.*.*

env:
  ARTIFACT_BIN: "nolus.tar.gz"
  ARTIFACT_SCRIPTS: "scripts.tar.gz"
  IMAGE_NAME: "public.ecr.aws/nolus/node"
  VERSION_TAG: ${{ github.ref_name }}
  IMAGE_DOCKERFILE: "./build/builder_spec.Dockerfile"
  ACCOUNTS_DIR: "accounts"
  CONTRACTS_INFO_FILE: "contracts-info.json"
  CONTRACTS_REPO: "github.com/Nolus-Protocol/nolus-money-market"
  SMART_CONTRACTS_ADMIN_ADDR: "nolus15jv5h5wjf3haljzfk5vcxx86n33rswsm7u3jgn" 
  FAUCET_TOKENS_DEV: "1000000000000$NLS_DENOM,1000000000000$STABLE_BANK_SYMBOL_DEV"
  STABLE_TICKER_DEV: "USDC"
  CONTRACTS_VERSION: "v0.2.9"
  
jobs:
  # Packs deploy scripts.
  prep-scripts:
    name: Prepare scripts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: |
          tar -czvf ${{ env.ARTIFACT_SCRIPTS }} scripts/remote scripts/common

      - name: Archive artifact scripts
        uses: actions/upload-artifact@v3
        with:
          name: scripts
          path: ${{ env.ARTIFACT_SCRIPTS }}

  # Builds new version of the binary.
  build-binary:
    name: Build binary
    runs-on: ubuntu-latest
    container:
      image: "public.ecr.aws/nolus/builder:0.7"

    steps:
    - uses: actions/checkout@v3

    # This is to fix GIT not liking owner of the checkout dir
    # Happens when executing not into the default container
    - name: Set ownership
      run: |
        chown -R $(id -u):$(id -g) $PWD

    - name: Run build binary
      run: |
        make build
        echo "Ensuring binary is statically linked ..."
        file target/release/nolusd | grep "statically linked"
        tar -C target/release/ -czvf $ARTIFACT_BIN .

    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: nolusd-${{ env.VERSION_TAG }}
        path: ${{ env.ARTIFACT_BIN }}

  # Using gh cli to download artifacts from 'nolus-money-market' repo.
  # https://cli.github.com/manual
  download-wasm:
    name: Download wasm contracts
    runs-on: ubuntu-latest
    
    env: 
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: List Releases
        run: | 
          gh release list --repo $CONTRACTS_REPO
      
      - name: Download wasm
        run: |
          gh release download --output wasm --repo $CONTRACTS_REPO $CONTRACTS_VERSION

      - name: Archive wasm
        uses: actions/upload-artifact@v3
        with:
          name: wasm-${{ env.CONTRACTS_VERSION }}
          path: wasm-${{ env.CONTRACTS_VERSION }}

  # Deploy a new version of the dev network.
  setup-dev-network:
    name: Setup dev network
    runs-on: ubuntu-latest
    needs: [build-binary, prep-scripts, download-wasm]
    container: amazon/aws-cli
    environment: dev chain

    steps:
      - name: Download scripts
        uses: actions/download-artifact@v3
        with:
          name: scripts

      - name: Download wasm
        uses: actions/download-artifact@v3
        with:
          name: wasm-${{ env.CONTRACTS_VERSION }}

      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: nolusd-${{ env.VERSION_TAG }}
        
      - name: Setup dev network
        run: |
          set -euox pipefail
          yum install -y tar gzip unzip jq
          tar -xvf $ARTIFACT_BIN
          export PATH="$(pwd)":$PATH

          ./scripts/init-dev-network.sh --artifact-bin $ARTIFACT_BIN --artifact-scripts $ARTIFACT_SCRIPTS
                --chain-id nolus-dev-1 -v 3 --validator-accounts-dir "$ACCOUNTS_DIR"
                --wasm-script-path "artifacts" --wasm-code-path "artifacts"
                --contracts-owner-addr "$SMART_CONTRACTS_ADMIN_ADDR"
                --treasury-nls-u128 "1000000000000"
                --faucet-mnemonic "${{ secrets.FAUCET_MNEMONIC_DEV }}"
                --faucet-tokens "$FAUCET_TOKENS_DEV"
                --lpp-native "$STABLE_TICKER_DEV"
                --contracts-info-file $CONTRACTS_INFO_FILE

      - name: Archive dev net data
        uses: actions/upload-artifact@v3
        with:
          name: dev-net-data-${{ env.VERSION_TAG }}
          path: |
            ${{ env.ACCOUNTS_DIR }}
            ${{ env.CONTRACTS_INFO_FILE }}
