name: Scheduled Test
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  test-fuzz:
    name: Run fuzz tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - uses: actions/checkout@v3
      
      - run: |
          make test-fuzz
