name: Test Fuzz
on:
  schedule:
    - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
  nondeterminism:
    name: Test App State Determinism
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25
      
      - uses: actions/checkout@v4

      - uses: "./.github/actions/private-go-modules"
        with:
          token: ${{ secrets.IBC_GO_TOKEN }}

      - run: |
          make test-sim-nondeterminism

  import-export:
    name: Test App Import Export
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - uses: actions/checkout@v4

      - uses: "./.github/actions/private-go-modules"
        with:
          token: ${{ secrets.IBC_GO_TOKEN }}

      - run: |
          make test-sim-import-export
